version: "3"

services:
  nshmp-site-ws:
    # Tomcat 8.5 with JRE 8 image
    image: usgsnshmp/tomcat:8.5-jre8 

    # Container name
    container_name: nshmp-site-ws__docker-compose

    # Restart always
    restart: always

    # Set port range 
    ports:
      - 8080-9080:8080

    # Look for changes to WAR file
    volumes:
      - ./build/libs/nshmp-site-ws.war:/usr/local/tomcat/webapps/nshmp-site-ws.war
